# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 08 Mar 2024 16:45:01 +0000
*	@admin	16
*	@ALL	1
*	@user	0
admin:*	@ALL	0
