<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: genchadt
 * Date: Wed, 13 Mar 2024 01:30:04 +0000
 */

$conf['title'] = 'The Collective Gaming Community';
$conf['template'] = 'mantinedoku';
$conf['tagline'] = 'Welcome in!';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['target']['extern'] = '_blank';
$conf['notify'] = 'thecollective_pz@protonmail.com';
$conf['registernotify'] = 'thecollective_pz@protonmail.com';
$conf['mailfrom'] = 'wiki-notify@thecollectivegc.com';
$conf['mailprefix'] = 'TCGC Wiki';
$conf['userewrite'] = '1';
$conf['plugin']['ckgedit']['gui'] = 'kama';
$conf['plugin']['discussion']['allowguests'] = 0;
$conf['plugin']['discussion']['showguests'] = 0;
$conf['plugin']['discussion']['visibilityButton'] = 1;
$conf['plugin']['discussion']['moderatorgroups'] = 'mod';
$conf['plugin']['dw2pdf']['output'] = 'browser';
$conf['plugin']['gallery']['options'] = 'cache,crop,lightbox';
$conf['plugin']['smtp']['smtp_host'] = 'mail.smtp2go.com';
$conf['plugin']['smtp']['smtp_port'] = 443;
$conf['plugin']['smtp']['smtp_ssl'] = 'ssl';
$conf['plugin']['smtp']['auth_user'] = 'thecollective.com';
$conf['plugin']['smtp']['auth_pass'] = '3jhSohn$42Uijn@dgNj^ot';
$conf['plugin']['vshare']['extrahard'] = 1;
$conf['plugin']['wrap']['darkTpl'] = 1;
$conf['tpl']['mikio']['showLightDark'] = '1';
$conf['tpl']['mikio']['autoLightDark'] = '1';
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'cyborg';
$conf['tpl']['bootstrap3']['showThemeSwitcher'] = '1';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
