# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Fri, 08 Mar 2024 16:45:01 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

krieger:$2y$10$Vgk9wZ9THvjV4YaaF9bvzuEq4AC2WdNITQAywv3T6eRqVPUZsVL62:Krieger:hunkuss@gmail.com:admin,user
dragonfly:$2y$10$wIHAop0GVX4gYcww1vf9X.PXkceHF76M8EkHNyePZNpoQSAx/1hL2:The Collective:thecollective_pz@protonmail.com:admin,mod,user
genchadt:$2y$10$FjiiqIP7s7oXlRuoTJfwHOzFELz8E9MPJ1mMSe8Kh3mvZTJ9/RyWW:GenChadT:timothy@caramail.com:admin,mod,user
